name: Test
on:
  pull_request:

jobs:
  gotest:
    name: Go test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.3
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/go/pkg/mod/cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependencies
        run: go mod download
      - name: Verify modules
        run: go mod verify
      - name: Tidy modules
        run: go mod tidy
      - name: go test
        run: go test -v -cover ./...
  connect_test:
    name: Connect test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker pull
        run: docker-compose pull
      - name: Docker build
        run: docker build -t dwh/redshift-view .
      - name: Connect test
        run: make test
